# listener format:
# listener=<listen_type>,<listen_ip>,<listen_port>,<type>
listener=tcp,0.0.0.0,8080,echo
listener=udp,0.0.0.0,8080,echo
listener=tcp,0.0.0.0,18080,proxy

# worker thread count
worker_num=4

# log config
log_level=info
log_file=/tmp/myserver.log
