# listener format:
# echo:  listener=<listen_type>,<listen_ip>,<listen_port>,echo
# proxy: listener=<listen_type>,<listen_ip>,<listen_port>,proxy,<target_ip>,<target_port>
listener=tcp,0.0.0.0,8080,echo
listener=udp,0.0.0.0,8080,echo
listener=tcp,0.0.0.0,18080,proxy,127.0.0.1,8080
listener=udp,0.0.0.0,18080,proxy,127.0.0.1,8080

# worker thread count
worker_num=4

# log config
log_level=info
log_file=/tmp/myserver.log
